name: publish
on: [push]
jobs:
  build-ocstore-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Build the ocstore Docker image
      run: |
            docker build . --tag ghcr.io/maksymbilenko/ocstore-php-apache:7.2-fpm
            docker push ghcr.io/maksymbilenko/ocstore-php-apache:7.2-fpm
